export const games = [
  {
    id: "minority",
    number: "01",
    title: "少数派を探せ",
    summary: "一人だけ違うお題。会話で浮いた人を見つける。",
    players: "3-8人",
    minutes: "5分",
    heat: 2,
    mood: "じわじわ",
    module: () => import("./minority.js"),
  },
  {
    id: "nominate",
    number: "02",
    title: "指名のグラス",
    summary: "一番それっぽい人を指名する、少し攻めた投票ゲーム。",
    players: "3人-",
    minutes: "3分",
    heat: 3,
    mood: "にぎやか",
    module: () => import("./nominate.js"),
  },
  {
    id: "question-pass",
    number: "03",
    title: "質問パス",
    summary: "答えるか、誰かに渡すか。距離感を選びながら回す。",
    players: "2人-",
    minutes: "10分",
    heat: 2,
    mood: "しっとり",
    module: () => import("./question-pass.js"),
  },
  {
    id: "color-guess",
    number: "04",
    title: "色あて",
    summary: "お題に合う色を直感で作って、近さやズレを楽しむ。",
    players: "2人-",
    minutes: "5分",
    heat: 1,
    mood: "直感",
    module: () => import("./color-guess.js"),
  },
  {
    id: "midnight-choice",
    number: "05",
    title: "深夜の二択",
    summary: "安全な二択から、少しだけ本音がこぼれる。",
    players: "2人-",
    minutes: "5分",
    heat: 2,
    mood: "大人寄り",
    module: () => import("./midnight-choice.js"),
  },
];
